<!-- 06 – DESENVOLVA UM JOGO EM QUE O COMPUTADOR ESCOLHE UM NÚMERO ALEATÓRIO E O
JOGADOR DEVE ADIVINHAR QUAL É. USE O LAÇO "ENQUANTO FAÇA" PARA PERMITIR MÚLTIPLAS
TENTATIVAS ATÉ O JOGADOR ACERTAR. -->