<!-- 07 – FAÇA UM PROGRAMA QUE PEDE AO USUÁRIO PARA DIGITAR VÁRIAS NOTAS, CALCULE A
MÉDIA DESSAS NOTAS E INFORME O RESULTADO. UTILIZE O LAÇO "ENQUANTO FAÇA" PARA
CONTINUAR PEDINDO NOTAS ATÉ QUE O USUÁRIO DECIDA PARAR.  -->